# Lesson 36

proc errorproc {x} {
	if { $x > 0 } {
		error "Error generated by error" "Info String for error" $x
	}
}

catch {errorproc}
puts "After bad proc call: ErrorCode: $errorCode"
puts "ERRORINFO:\n$errorInfo\n"

set errorInfo "";
catch {errorproc 0}
puts "After proc call with no errors: ErrorCode: $errorCode"
puts "ERRORINFO:\n$errorInfo\n"

catch {errorproc 2}
puts "after error generated in proc: ErrorCode: $errorCode"
puts "ERRORINFO:\n$errorInfo\n"

proc returnErr { x } {
	return -code error -errorinfo "Return Generates This" -errorcode "-999"
}

catch { returnErr 2 }
puts "after proc that uses return to generate an error:"
puts "	ErrorCode: $errorCode"
puts "ERRORINFO:\n$errorInfo\n"

proc withErr {x} {
	set x $a
}

catch {withErr 2}
puts "after proc with an error: ErrorCode: $errorCode"
puts "ERRORINFO:\n$errorInfo\n"

catch {open [file join no_such_dir wrong_file] r}
puts "after an error call to non existing file:"
puts "ErrorCode: $errorCode"
puts "ERRORINFO: $errorInfo"


